# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Adam Saunders Research
email: '&#58;s&#37;6&#49;%&#55;5nd&#101;rs%2E&#97;d&#97;&#109;9%3&#55;&#64;g%6D%61i%&#54;C&#46;&#99;&#111;&#109;'
html_email: sau&#110;&#100;ers&#46;adam9&#55;&#64;gmail&#46;c&#111;&#109;
description: >- # this means to ignore newlines until "baseurl:"
  Adam Saunders is a electrical engineering student at the 
  University of Dayton interested in pursuing medical 
  image processing research. 
twitter_username: AdamSaunders97
github_username: saundersresearch
linkedin_username: adamsaunders97
#repository: saundersresearch/site
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Adam Saunders"
  avatar : "/assets/images/headshot_square.jpg"
  bio    : "I am an electrical engineering student interested in medical image processing."
  links:
    - label: "Email"
      icon: "fa fa-envelope"
      url: "mailto:s&#37;6&#49;%&#55;5nd&#101;rs%2E&#97;d&#97;&#109;9%3&#55;&#64;g%6D%61i%&#54;C&#46;&#99;&#111;&#109;"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/adamsaunders97"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/AdamSaunders97"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://sigmoid.social/@adamsaunders"

footer:
  links: 
    - label: "Email"
      icon: "fa fa-envelope"
      url: "mailto:s&#37;6&#49;%&#55;5nd&#101;rs%2E&#97;d&#97;&#109;9%3&#55;&#64;g%6D%61i%&#54;C&#46;&#99;&#111;&#109;"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/adamsaunders97"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/AdamSaunders97"    
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://sigmoid.social/@adamsaunders"
      rel: "me"

atom_feed:
  hide: false

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

social:
  type: Person
  name: Adam Saunders
  links:
    - "https://twitter.com/AdamSaunders97"
    - "https://www.linkedin.com/in/adamsaunders97"
    - "https://sigmoid.social/@adamsaunders"
