# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Adam Saunders Research
# Email obfuscator: https://www.albionresearch.com/tools/obfuscator
email: '&#109;ai&#108;&#116;o&#58;a&#100;&#97;m&#46;m%2Es&#97;u%6Eders&#64;%76a%6Ede&#114;b&#37;&#54;9&#108;t&#46;edu'
html_email: '&#97;d&#97;m&#46;m&#46;s&#97;u&#110;ders&#64;&#118;ande&#114;bilt&#46;edu'
description: >- # this means to ignore newlines until "baseurl:"
  Adam Saunders is a electrical engineering PhD 
  student at Vanderbilt University working in medical
  imaging research.
twitter_username: AdamSaunders97
bluesky_username: adamsaunders.net
github_username: saundersresearch
linkedin_username: adamsaunders97
repository: saundersresearch/saundersresearch.github.io
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Chicago # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - .well-known

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Adam Saunders"
  avatar : "/assets/images/headshot_square.jpg"
  bio    : "I am a PhD student researching medical imaging."
  links:
    - label: "Email"
      icon: "fa fa-envelope"
      url: "mailto:&#109;ai&#108;&#116;o&#58;a&#100;&#97;m&#46;m%2Es&#97;u%6Eders&#64;%76a%6Ede&#114;b&#37;&#54;9&#108;t&#46;edu"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/adamsaunders97"
    - label: "BlueSky"
      icon: "fab fa-bluesky"
      url: "https://bsky.app/profile/saundersresearch.github.io"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/saundersresearch"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/AdamSaunders97"
    # - label: "Mastodon"
    #   icon: "fab fa-fw fa-mastodon"
    #   url: "https://sigmoid.social/@adamsaunders"

footer:
  links: 
    - label: "Email"
      icon: "fa fa-envelope"
      url: "mailto:&#109;ai&#108;&#116;o&#58;a&#100;&#97;m&#46;m%2Es&#97;u%6Eders&#64;%76a%6Ede&#114;b&#37;&#54;9&#108;t&#46;edu"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/adamsaunders97"
    - label: "BlueSky"
      icon: "fab fa-bluesky"
      url: "https://bsky.app/profile/saundersresearch.github.io"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/saundersresearch"
    # - label: "Mastodon"
    #   icon: "fab fa-fw fa-mastodon"
    #   url: "https://sigmoid.social/@adamsaunders"
    #   rel: "me"

atom_feed:
  hide: false

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

social:
  type: Person
  name: Adam Saunders
  links:
    - "https://twitter.com/AdamSaunders97"
    - "https://www.linkedin.com/in/adamsaunders97"
    # - "https://sigmoid.social/@adamsaunders"

comments:
  provider: "giscus"
  giscus:
    repo_id              : R_kgDOHz-69w # Shown during giscus setup at https://giscus.app
    category_name        : Announcements # Full text name of the category
    category_id          : DIC_kwDOHz-6984Cw2Io # Shown during giscus setup at https://giscus.app
    discussion_term      : pathname # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : 1 # '1' for enabled (default), '0' for disabled
    theme                : light_high_contrast # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
